name: suite2p-dev
dependencies:
  # All of these should match environment.yml
  - python>=3.7,<3.8
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - h5py
  - scikit-learn
  - pyqt
  - pyqtgraph
  - natsort
  - pip:
    - rastermap>0.1.0
    - tifffile
    - scanimage-tiff-reader
    # Dev-specific dependencies (can be different from environment.yml)
    - sphinx>=3.0
    - sphinxcontrib-apidoc
    - sphinx_rtd_theme
