name: suite2p
channels:
  - pytorch
  - numba
dependencies:
  - python>=3.8,<3.9
  - pip
  - mkl
  - tbb
  - numpy
  - numba
  - matplotlib
  - scikit-learn
  - h5py=2.10.0
  - pip:
    - scipy>=1.4.0
    - pyqt5
    - pyqt5.sip
    - pyqt5-tools
    - torch>=1.7.1
    - natsort
    - rastermap>0.1.0
    - tifffile
    - scanimage-tiff-reader>=1.4.1
    - pyqtgraph
    - importlib-metadata
    - paramiko
    - pynwb
    - sbxreader
    - suite2p
