name: suite2p
channels:
  - conda-forge
dependencies:
  - python>=3.7.6,<3.8
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - tbb
  - numpy<1.19.0
  - numba<0.50.0
  - matplotlib
  - scipy
  - scikit-learn
  - pyqt
  - pip:
    - h5py==2.10.0
    - natsort
    - rastermap>0.1.0
    - tifffile
    - scanimage-tiff-reader>=1.4.1
    - pyqtgraph
    - importlib-metadata
    - paramiko
    - pynwb
    - sbxreader
    - suite2p
