site_name: Suite2p Documentation
theme:
  name: readthedocs  # You can also use 'readthedocs' or other themes

nav:
  - Home: index.md
  - Basics:
      - Installation: installation.md
      - Inputs: inputs.md
  - Settings: settings.md
  - Using the GUI: gui.md
  - Outputs: outputs.md
  - Multiday recordings: multiday.md
  - Frequently asked questions: FAQ.md
  - How it Works:
      - Registration: registration.md
      - Cell Detection: celldetection.md
      - Signal Extraction: roiextraction.md
      - Spike Deconvolution: deconvolution.md

markdown_extensions:
  - admonition
  - toc
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.details

