site_name: Suite2p Documentation
theme:
  name: readthedocs  # You can also use 'readthedocs' or other themes

nav:
  - Home: index.md
  - Basics:
      - Installation: installation.md
      - Inputs: inputs.md
  - Settings: settings.md
  - Using the GUI: gui.md
  - Outputs:
      - MATLAB: outputs.md#matlab-output
      - NWB: outputs.md#nwb-output
      - Stat Fields: outputs.md#stat-npy-fields
  - Multiday Recordings: multiday.md
  - Developer Docs:
      - Versioning: developer_doc.md#versioning
      - Testing: developer_doc.md#testing
  - FAQ: FAQ.md
  - How it Works:
      - Registration: registration.md
      - Cell Detection: celldetection.md
      - Signal Extraction: roiextraction.md
      - Spike Deconvolution: deconvolution.md

markdown_extensions:
  - toc
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tabbed
  - pymdownx.details

